-- MINI-APLICATIE INSTAGRAM

-- Tabelul utilizatori
CREATE TABLE utilizatori (
    id_utilizator NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nume VARCHAR2(100) NOT NULL
);

-- Tabelul prieteni (urmăriri unidirecționale)
CREATE TABLE prieteni (
    id_user1 NUMBER(10) NOT NULL, -- urmărește
    id_user2 NUMBER(10) NOT NULL, -- este urmărit
    CONSTRAINT pk_prieteni PRIMARY KEY (id_user1, id_user2),
    CONSTRAINT fk_user1 FOREIGN KEY (id_user1) REFERENCES utilizatori(id_utilizator),
    CONSTRAINT fk_user2 FOREIGN KEY (id_user2) REFERENCES utilizatori(id_utilizator),
    CONSTRAINT chk_not_self_friend CHECK (id_user1 != id_user2)
);

-- Tabelul postari
CREATE TABLE postari (
    id_postare NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user NUMBER(10) NOT NULL,
    continut VARCHAR2(1000),
    data_postarii DATE DEFAULT SYSDATE,
    CONSTRAINT fk_postare_user FOREIGN KEY (id_user) REFERENCES utilizatori(id_utilizator)
);

-- INSERARE
INSERT INTO utilizatori (nume) VALUES ('Ana Pop');
INSERT INTO utilizatori (nume) VALUES ('Dan Ionescu');
INSERT INTO utilizatori (nume) VALUES ('Maria Radu');
INSERT INTO utilizatori (nume) VALUES ('Alex Dima');
INSERT INTO utilizatori (nume) VALUES ('Ioana Marinescu');
INSERT INTO utilizatori (nume) VALUES ('Vlad Georgescu');
INSERT INTO utilizatori (nume) VALUES ('Elena Stoica');
INSERT INTO utilizatori (nume) VALUES ('Robert Munteanu');
INSERT INTO utilizatori (nume) VALUES ('Diana Neagu');
INSERT INTO utilizatori (nume) VALUES ('Cristian Enache');

-- useri fara postari
INSERT INTO utilizatori (nume) VALUES ('Andreea Mihai');
INSERT INTO utilizatori (nume) VALUES ('Mihnea Drăghici');
INSERT INTO utilizatori (nume) VALUES ('Corina Vasilescu');
INSERT INTO utilizatori (nume) VALUES ('Florin Toma');
INSERT INTO utilizatori (nume) VALUES ('Bianca Marinescu');


INSERT INTO prieteni (id_user1, id_user2) VALUES (1, 2);
INSERT INTO prieteni (id_user1, id_user2) VALUES (1, 3);
INSERT INTO prieteni (id_user1, id_user2) VALUES (1, 4);
INSERT INTO prieteni (id_user1, id_user2) VALUES (2, 3);
INSERT INTO prieteni (id_user1, id_user2) VALUES (2, 5);
INSERT INTO prieteni (id_user1, id_user2) VALUES (3, 6);
INSERT INTO prieteni (id_user1, id_user2) VALUES (3, 1);
INSERT INTO prieteni (id_user1, id_user2) VALUES (4, 5);
INSERT INTO prieteni (id_user1, id_user2) VALUES (4, 6);
INSERT INTO prieteni (id_user1, id_user2) VALUES (4, 7);
INSERT INTO prieteni (id_user1, id_user2) VALUES (5, 8);
INSERT INTO prieteni (id_user1, id_user2) VALUES (6, 2);
INSERT INTO prieteni (id_user1, id_user2) VALUES (6, 3);
INSERT INTO prieteni (id_user1, id_user2) VALUES (7, 4);
INSERT INTO prieteni (id_user1, id_user2) VALUES (7, 1);
INSERT INTO prieteni (id_user1, id_user2) VALUES (8, 9);
INSERT INTO prieteni (id_user1, id_user2) VALUES (9, 10);
INSERT INTO prieteni (id_user1, id_user2) VALUES (10, 1);
INSERT INTO prieteni (id_user1, id_user2) VALUES (10, 2);
INSERT INTO prieteni (id_user1, id_user2) VALUES (10, 3);


-- Ana (id 1) - 4 postări
INSERT INTO postari (id_user, continut, data_postarii) VALUES (1, 'Zi frumoasă de primăvară!', TO_DATE('2024-03-01','YYYY-MM-DD'));
INSERT INTO postari (id_user, continut, data_postarii) VALUES (1, 'SQL e chiar fun!', TO_DATE('2024-03-03','YYYY-MM-DD'));
INSERT INTO postari (id_user, continut) VALUES (1, 'Am terminat serialul!');
INSERT INTO postari (id_user, continut) VALUES (1, 'Cafea, cărți și liniște.');

-- Dan (2) - 3 postări
INSERT INTO postari (id_user, continut, data_postarii) VALUES (2, 'Buna, tuturor!', TO_DATE('2024-03-10','YYYY-MM-DD'));
INSERT INTO postari (id_user, continut) VALUES (2, 'Învăț Oracle SQL.');
INSERT INTO postari (id_user, continut) VALUES (2, 'Seară de coding.');

-- Maria (3) - 5 postări
INSERT INTO postari (id_user, continut, data_postarii) VALUES (3, 'Sesiune si stres!', TO_DATE('2025-03-01','YYYY-MM-DD'));
INSERT INTO postari (id_user, continut, data_postarii) VALUES (3, 'În vacanță la munte!', TO_DATE('2024-03-22','YYYY-MM-DD'));
INSERT INTO postari (id_user, continut, data_postarii) VALUES (3, 'Apusuri superbe.', TO_DATE('2024-03-12','YYYY-MM-DD'));
INSERT INTO postari (id_user, continut) VALUES (3, 'Dimineți de weekend.');
INSERT INTO postari (id_user, continut) VALUES (3, 'Încerc o nouă rețetă.');

-- Alex (4) - 4 postări
INSERT INTO postari (id_user, continut, data_postarii) VALUES (4, 'Azi am fost productiv.', sysdate);
INSERT INTO postari (id_user, continut) VALUES (4, 'Aștept weekendul.');
INSERT INTO postari (id_user, continut) VALUES (4, 'Citeam despre baze de date.');
INSERT INTO postari (id_user, continut, data_postarii) VALUES (4, 'Plimbare în parc.',TO_DATE('2024-03-20','YYYY-MM-DD'));

-- Ioana (5) - 3 postări
INSERT INTO postari (id_user, continut) VALUES (5, 'Cafea cu prieteni.');
INSERT INTO postari (id_user, continut) VALUES (5, 'Un nou început.');
INSERT INTO postari (id_user, continut) VALUES (5, 'Primăvara a sosit.');

-- Vlad (6) - 2 postări
INSERT INTO postari (id_user, continut) VALUES (6, 'Maraton de filme.');
INSERT INTO postari (id_user, continut) VALUES (6, 'Somn, mâncare, repaus.');

-- Elena (7) - 3 postări
INSERT INTO postari (id_user, continut) VALUES (7, 'Creez ceva nou!');
INSERT INTO postari (id_user, continut) VALUES (7, 'Florile mele înfloresc!');
INSERT INTO postari (id_user, continut) VALUES (7, 'Zi senină!');

-- Robert (8) - 2 postări
INSERT INTO postari (id_user, continut) VALUES (8, 'Gata cu munca pe azi!');
INSERT INTO postari (id_user, continut) VALUES (8, 'Explorări urbane.');

-- Diana (9) - 2 postări
INSERT INTO postari (id_user, continut) VALUES (9, 'Book club');
INSERT INTO postari (id_user, continut) VALUES (9, 'Testez o nouă aplicație.');

-- Cristian (10) - 2 postări
INSERT INTO postari (id_user, continut) VALUES (10, 'SQL master incoming.');
INSERT INTO postari (id_user, continut) VALUES (10, 'Am finalizat proiectul!!!');

commit;


select * from utilizatori;
select * from postari;
select * from prieteni;


-- 1.
SELECT u.id_utilizator, nume, id_postare, continut
from utilizatori u left join postari p on (u.id_utilizator = p.id_user)
ORDER by data_postarii DESC NULLS LAST;


-- 2.
SELECT u.id_utilizator, u.nume, continut, TO_CHAR(data_postarii, 'DD.MM.YYYY')
from utilizatori u join prieteni p1 on (u.id_utilizator = p1.id_user1)
                   join prieteni p2 on (u.id_utilizator = p2.id_user2)
                   left join postari p on (u.id_utilizator = p.id_user)
WHERE p1.id_user2 = 1 AND p2.id_user1 = 1
AND TO_char(data_postarii, 'MON') = 'MAR' AND TO_char(data_postarii, 'YYYY') = 2024;


