# -*- coding: utf-8 -*-
"""L3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NdvHceplAAPXRnBi8Ec09Ff-3RaclakL

COMPREHENSION LIST

* l = [ceva for ...]
* l = [ceva for ... if ...]
* l = [ceva if ... altceva else for ...]
"""

l = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
print(l[1:])
print(l[1:5])
print(l[1:5:2])
print(l[::2])
print(l[8:])

"""=================== EXERCITII =================="""

#E1
print([word for word in input("Scrieti propozitie:").split() if (word[0].lower() in 'aeiou')])

#E3
print("".join([x+"p"+x.lower() if (x.lower() in 'aeiou') else x for x in input("Scrieti propozitia:")]))

#E4
print([chr(x) for x in range(ord('a'), ord('z')+1)])

#E5
print([-x if (x%2==0) else x for x in range(1, int(input("n="))+1)])

#E6
print([int(x) for x in input("Lista numere:").split() if (int(x)%2==1)])

#E7
x = input("Lista numere").split()
print([int(x[i]) for i in range(1, len(x), 2)])

#E8
x = input("Lista numere").split()
print([int(x[i]) for i in range(len(x)) if ((int(x[i])-i)%2==0)])
#2 4 1 7 5 1 8 10

#E9
x = input("Lista numere").split()
print([(int(x[i]), int(x[i+1])) for i in range(len(x)-1)])

#E10
x = input()
print([x[i::]+x[:i:] for i in range(0, len(x))])

#E11
l1 = input().split()
l2 = input().split()
l1[::2] = l2[::2]
print(l1)

#E12
k = int(input())
l = input().split()
aux = l[k:]
print(aux)

#E13
l = input().split()

i=0
ok = 0
while (i<len(l) and ok==0):
  if (int(l[i])==0):
    ok = 1
  i+=1

p1 = i-1

ok = 0
while (i<len(l) and ok==0):
  if (int(l[i])==0):
    ok = 1
  i+=1

p2 = i

new = l[:p1] + l[p2:]
print(new)

#3 4 5 0 6 7 8 2 0 5 2 4

#E14
l = input().split()

newl = []
for i in range(len(l)):
  if (int(l[i])!=0):
    newl.append(l[i])

print(newl)
