# -*- coding: utf-8 -*-
"""PA_lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14bMNQSut3J7qS6vUdtrmAsuQs3b7E5FU

#INTRODUCERE

ANACONDA - Spyder

'#%%' --> pentru o celula noua

LA TEST PYTHON: AVEM VOIE CU DOCUMENTATIA PYTHON!!

o sa dam pe calculatoarele din lab
"""

a = int(input())
b = int(input())
print(a+b)

"""ai grija in cazul asta daca pui a = 7 de ex si b = 8.3 la citire (o sa dea eroare)

aici merge sa pui b = int(float(input()))
"""

# daca vrem sa citim numere de pe aceeasi linie

a,b = input().split()
a = int(a)
b = int(b)
print(a+b)

a,b,c = input().split()
a = int(a)
b = int(b)
print(a+b)

l = input()
print(l)

a = "mama"
b = 5
c = "mere"
d = 4.5

print(a, b, c, d, end="@@@@")
print(a, b, c, d, sep='***')

print(a, "are", b, c, "si", d, "kg de pere")
print(a + " are " + str(b) + " " + c + " si " + str(d) + " kg de pere")
print("%s are %d %s si %f kg de pere"%(a, b, c, d))
print("%s are %d %s si %g kg de pere"%(a, b, c, d)) # %g - face numar minim de zecimale

print("{} are {} {} si {} kg de pere".format(a, b, c, d))
print("{2} are {1} {0} si {3} kg de pere".format(a, b, c, d))
print(f"{a} are {b} {c} si {d} kg de pere")
print(f"{a} are {b} {c} si {d:.5f} kg de pere") # sa il afiseze pe d cu 5 zecimale dupa virgula
print(f"{a} are {b:07} {c} si {d:.5f} kg de pere")

b=58
print(f"{a} are {b:07} {c} si {d:.5f} kg de pere")

a=7
b=3

if a<b:
  print("DA")
else:
  print("NU")

a=7
b=3

if a<b:
  print("DA")
else:
  if a==b:
    print("egale")
  else:
    print("NU")

a=7
b=3

if a<b:
  print("DA")
elif a==b:
    print("egale")
else:
    print("NU")

"""#EXERCITII"""

#E1
a,b = input().split()
a = int(a)
b = int(b)
print(f"suma numerelor {a} si {b} este {a+b}, iar produsul este {a*b}")

#E2
a,b,c = input().split()
a = int(a)
b = int(b)
c = int(c)

if (0<=a & a<24) & (0<=b & b<60) & (0<=c & c<60):
  print(f"{a:02}:{b:02}:{c:02}")
else:
  print("NU")

#E2

z,l,a = input().split()
z = int(z)
l = int(l)
a = int(a)

if z<28:
  print(f"{(z+1):02}.{l:02}.{a:02}")
else:
  if z==28:
    if l!=2:
      print(f"{(z+1):02}.{l:02}.{a:02}")
    else: #este februarie
      if (a%400==0) | ((a%4==0) & (a%100!=0)):
        print(f"{(z+1):02}.{l:02}.{a:02}")
      else:
        print(f"01.03.{a:02}")
  else:
    if z==29:
      print(f"{(z+1):02}.{l:02}.{a:02}")
    elif z==30:
      if l==1 or l==3 or l==5 or l==7 or l==8 or l==10 or l==12:
        print(f"{(z+1):02}.{l:02}.{a:02}")
      else:
        print(f"01.{(l+1):02}.{a:02}")
    elif z==31:
      if l<12:
        print(f"01.{(l+1):02}.{a:02}")
      else:
        print(f"01.01.{(a+1):02}")
